// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientGetDiscovery.proto

package net.iGap.proto;

public final class ProtoClientGetDiscovery {
  private ProtoClientGetDiscovery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientGetDiscoveryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ClientGetDiscovery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional uint32 page_id = 2;</code>
     */
    int getPageId();

    /**
     * <code>optional uint32 project_id = 3;</code>
     */
    int getProjectId();
  }
  /**
   * Protobuf type {@code proto.ClientGetDiscovery}
   */
  public  static final class ClientGetDiscovery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ClientGetDiscovery)
      ClientGetDiscoveryOrBuilder {
    // Use ClientGetDiscovery.newBuilder() to construct.
    private ClientGetDiscovery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientGetDiscovery() {
      pageId_ = 0;
      projectId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientGetDiscovery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              pageId_ = input.readUInt32();
              break;
            }
            case 24: {

              projectId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscovery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscovery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.class, net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int PAGE_ID_FIELD_NUMBER = 2;
    private int pageId_;
    /**
     * <code>optional uint32 page_id = 2;</code>
     */
    public int getPageId() {
      return pageId_;
    }

    public static final int PROJECT_ID_FIELD_NUMBER = 3;
    private int projectId_;
    /**
     * <code>optional uint32 project_id = 3;</code>
     */
    public int getProjectId() {
      return projectId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (pageId_ != 0) {
        output.writeUInt32(2, pageId_);
      }
      if (projectId_ != 0) {
        output.writeUInt32(3, projectId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (pageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, pageId_);
      }
      if (projectId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, projectId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery other = (net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (getPageId()
          == other.getPageId());
      result = result && (getProjectId()
          == other.getProjectId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + PAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPageId();
      hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProjectId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientGetDiscovery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClientGetDiscovery)
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscovery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscovery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.class, net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        pageId_ = 0;

        projectId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscovery_descriptor;
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery getDefaultInstanceForType() {
        return net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.getDefaultInstance();
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery build() {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery buildPartial() {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery result = new net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.pageId_ = pageId_;
        result.projectId_ = projectId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery) {
          return mergeFrom((net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery other) {
        if (other == net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getPageId() != 0) {
          setPageId(other.getPageId());
        }
        if (other.getProjectId() != 0) {
          setProjectId(other.getProjectId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private int pageId_ ;
      /**
       * <code>optional uint32 page_id = 2;</code>
       */
      public int getPageId() {
        return pageId_;
      }
      /**
       * <code>optional uint32 page_id = 2;</code>
       */
      public Builder setPageId(int value) {
        
        pageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 page_id = 2;</code>
       */
      public Builder clearPageId() {
        
        pageId_ = 0;
        onChanged();
        return this;
      }

      private int projectId_ ;
      /**
       * <code>optional uint32 project_id = 3;</code>
       */
      public int getProjectId() {
        return projectId_;
      }
      /**
       * <code>optional uint32 project_id = 3;</code>
       */
      public Builder setProjectId(int value) {
        
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 project_id = 3;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientGetDiscovery)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientGetDiscovery)
    private static final net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery();
    }

    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientGetDiscovery>
        PARSER = new com.google.protobuf.AbstractParser<ClientGetDiscovery>() {
      public ClientGetDiscovery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientGetDiscovery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientGetDiscovery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientGetDiscovery> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscovery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientGetDiscoveryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ClientGetDiscoveryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    java.util.List<net.iGap.proto.ProtoGlobal.Discovery> 
        getDiscoveriesList();
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    net.iGap.proto.ProtoGlobal.Discovery getDiscoveries(int index);
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    int getDiscoveriesCount();
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    java.util.List<? extends net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder> 
        getDiscoveriesOrBuilderList();
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder getDiscoveriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ClientGetDiscoveryResponse}
   */
  public  static final class ClientGetDiscoveryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ClientGetDiscoveryResponse)
      ClientGetDiscoveryResponseOrBuilder {
    // Use ClientGetDiscoveryResponse.newBuilder() to construct.
    private ClientGetDiscoveryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientGetDiscoveryResponse() {
      title_ = "";
      discoveries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientGetDiscoveryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                discoveries_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.Discovery>();
                mutable_bitField0_ |= 0x00000004;
              }
              discoveries_.add(
                  input.readMessage(net.iGap.proto.ProtoGlobal.Discovery.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          discoveries_ = java.util.Collections.unmodifiableList(discoveries_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscoveryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscoveryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.class, net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCOVERIES_FIELD_NUMBER = 3;
    private java.util.List<net.iGap.proto.ProtoGlobal.Discovery> discoveries_;
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    public java.util.List<net.iGap.proto.ProtoGlobal.Discovery> getDiscoveriesList() {
      return discoveries_;
    }
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    public java.util.List<? extends net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder> 
        getDiscoveriesOrBuilderList() {
      return discoveries_;
    }
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    public int getDiscoveriesCount() {
      return discoveries_.size();
    }
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    public net.iGap.proto.ProtoGlobal.Discovery getDiscoveries(int index) {
      return discoveries_.get(index);
    }
    /**
     * <code>repeated .proto.Discovery discoveries = 3;</code>
     */
    public net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder getDiscoveriesOrBuilder(
        int index) {
      return discoveries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      for (int i = 0; i < discoveries_.size(); i++) {
        output.writeMessage(3, discoveries_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      for (int i = 0; i < discoveries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, discoveries_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse other = (net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getDiscoveriesList()
          .equals(other.getDiscoveriesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getDiscoveriesCount() > 0) {
        hash = (37 * hash) + DISCOVERIES_FIELD_NUMBER;
        hash = (53 * hash) + getDiscoveriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientGetDiscoveryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClientGetDiscoveryResponse)
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscoveryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscoveryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.class, net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDiscoveriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        title_ = "";

        if (discoveriesBuilder_ == null) {
          discoveries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          discoveriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoClientGetDiscovery.internal_static_proto_ClientGetDiscoveryResponse_descriptor;
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.getDefaultInstance();
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse build() {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse buildPartial() {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse result = new net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.title_ = title_;
        if (discoveriesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            discoveries_ = java.util.Collections.unmodifiableList(discoveries_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.discoveries_ = discoveries_;
        } else {
          result.discoveries_ = discoveriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse) {
          return mergeFrom((net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse other) {
        if (other == net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (discoveriesBuilder_ == null) {
          if (!other.discoveries_.isEmpty()) {
            if (discoveries_.isEmpty()) {
              discoveries_ = other.discoveries_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDiscoveriesIsMutable();
              discoveries_.addAll(other.discoveries_);
            }
            onChanged();
          }
        } else {
          if (!other.discoveries_.isEmpty()) {
            if (discoveriesBuilder_.isEmpty()) {
              discoveriesBuilder_.dispose();
              discoveriesBuilder_ = null;
              discoveries_ = other.discoveries_;
              bitField0_ = (bitField0_ & ~0x00000004);
              discoveriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDiscoveriesFieldBuilder() : null;
            } else {
              discoveriesBuilder_.addAllMessages(other.discoveries_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.util.List<net.iGap.proto.ProtoGlobal.Discovery> discoveries_ =
        java.util.Collections.emptyList();
      private void ensureDiscoveriesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          discoveries_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.Discovery>(discoveries_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Discovery, net.iGap.proto.ProtoGlobal.Discovery.Builder, net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder> discoveriesBuilder_;

      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.Discovery> getDiscoveriesList() {
        if (discoveriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(discoveries_);
        } else {
          return discoveriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public int getDiscoveriesCount() {
        if (discoveriesBuilder_ == null) {
          return discoveries_.size();
        } else {
          return discoveriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Discovery getDiscoveries(int index) {
        if (discoveriesBuilder_ == null) {
          return discoveries_.get(index);
        } else {
          return discoveriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder setDiscoveries(
          int index, net.iGap.proto.ProtoGlobal.Discovery value) {
        if (discoveriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiscoveriesIsMutable();
          discoveries_.set(index, value);
          onChanged();
        } else {
          discoveriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder setDiscoveries(
          int index, net.iGap.proto.ProtoGlobal.Discovery.Builder builderForValue) {
        if (discoveriesBuilder_ == null) {
          ensureDiscoveriesIsMutable();
          discoveries_.set(index, builderForValue.build());
          onChanged();
        } else {
          discoveriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder addDiscoveries(net.iGap.proto.ProtoGlobal.Discovery value) {
        if (discoveriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiscoveriesIsMutable();
          discoveries_.add(value);
          onChanged();
        } else {
          discoveriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder addDiscoveries(
          int index, net.iGap.proto.ProtoGlobal.Discovery value) {
        if (discoveriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiscoveriesIsMutable();
          discoveries_.add(index, value);
          onChanged();
        } else {
          discoveriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder addDiscoveries(
          net.iGap.proto.ProtoGlobal.Discovery.Builder builderForValue) {
        if (discoveriesBuilder_ == null) {
          ensureDiscoveriesIsMutable();
          discoveries_.add(builderForValue.build());
          onChanged();
        } else {
          discoveriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder addDiscoveries(
          int index, net.iGap.proto.ProtoGlobal.Discovery.Builder builderForValue) {
        if (discoveriesBuilder_ == null) {
          ensureDiscoveriesIsMutable();
          discoveries_.add(index, builderForValue.build());
          onChanged();
        } else {
          discoveriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder addAllDiscoveries(
          java.lang.Iterable<? extends net.iGap.proto.ProtoGlobal.Discovery> values) {
        if (discoveriesBuilder_ == null) {
          ensureDiscoveriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, discoveries_);
          onChanged();
        } else {
          discoveriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder clearDiscoveries() {
        if (discoveriesBuilder_ == null) {
          discoveries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          discoveriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public Builder removeDiscoveries(int index) {
        if (discoveriesBuilder_ == null) {
          ensureDiscoveriesIsMutable();
          discoveries_.remove(index);
          onChanged();
        } else {
          discoveriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Discovery.Builder getDiscoveriesBuilder(
          int index) {
        return getDiscoveriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder getDiscoveriesOrBuilder(
          int index) {
        if (discoveriesBuilder_ == null) {
          return discoveries_.get(index);  } else {
          return discoveriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public java.util.List<? extends net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder> 
           getDiscoveriesOrBuilderList() {
        if (discoveriesBuilder_ != null) {
          return discoveriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(discoveries_);
        }
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Discovery.Builder addDiscoveriesBuilder() {
        return getDiscoveriesFieldBuilder().addBuilder(
            net.iGap.proto.ProtoGlobal.Discovery.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Discovery.Builder addDiscoveriesBuilder(
          int index) {
        return getDiscoveriesFieldBuilder().addBuilder(
            index, net.iGap.proto.ProtoGlobal.Discovery.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Discovery discoveries = 3;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.Discovery.Builder> 
           getDiscoveriesBuilderList() {
        return getDiscoveriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Discovery, net.iGap.proto.ProtoGlobal.Discovery.Builder, net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder> 
          getDiscoveriesFieldBuilder() {
        if (discoveriesBuilder_ == null) {
          discoveriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.Discovery, net.iGap.proto.ProtoGlobal.Discovery.Builder, net.iGap.proto.ProtoGlobal.DiscoveryOrBuilder>(
                  discoveries_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          discoveries_ = null;
        }
        return discoveriesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientGetDiscoveryResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientGetDiscoveryResponse)
    private static final net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse();
    }

    public static net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientGetDiscoveryResponse>
        PARSER = new com.google.protobuf.AbstractParser<ClientGetDiscoveryResponse>() {
      public ClientGetDiscoveryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientGetDiscoveryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientGetDiscoveryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientGetDiscoveryResponse> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoClientGetDiscovery.ClientGetDiscoveryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientGetDiscovery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientGetDiscovery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientGetDiscoveryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientGetDiscoveryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ClientGetDiscovery.proto\022\005proto\032\rReque" +
      "st.proto\032\016Response.proto\032\014Global.proto\"Z" +
      "\n\022ClientGetDiscovery\022\037\n\007request\030\001 \001(\0132\016." +
      "proto.Request\022\017\n\007page_id\030\002 \001(\r\022\022\n\nprojec" +
      "t_id\030\003 \001(\r\"u\n\032ClientGetDiscoveryResponse" +
      "\022!\n\010response\030\001 \001(\0132\017.proto.Response\022\r\n\005t" +
      "itle\030\002 \001(\t\022%\n\013discoveries\030\003 \003(\0132\020.proto." +
      "DiscoveryB)\n\016net.iGap.protoB\027ProtoClient" +
      "GetDiscoveryb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        }, assigner);
    internal_static_proto_ClientGetDiscovery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ClientGetDiscovery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientGetDiscovery_descriptor,
        new java.lang.String[] { "Request", "PageId", "ProjectId", });
    internal_static_proto_ClientGetDiscoveryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ClientGetDiscoveryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientGetDiscoveryResponse_descriptor,
        new java.lang.String[] { "Response", "Title", "Discoveries", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
