// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MplTransactionList.proto

package net.iGap.proto;

public final class ProtoMplTransactionList {
  private ProtoMplTransactionList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MplTransactionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplTransactionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .proto.MplTransaction.Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .proto.MplTransaction.Type type = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.MplTransaction.Type getType();

    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    boolean hasPagination();
    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    net.iGap.proto.ProtoGlobal.Pagination getPagination();
    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder();
  }
  /**
   * Protobuf type {@code proto.MplTransactionList}
   */
  public  static final class MplTransactionList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplTransactionList)
      MplTransactionListOrBuilder {
    // Use MplTransactionList.newBuilder() to construct.
    private MplTransactionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplTransactionList() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MplTransactionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              net.iGap.proto.ProtoGlobal.Pagination.Builder subBuilder = null;
              if (pagination_ != null) {
                subBuilder = pagination_.toBuilder();
              }
              pagination_ = input.readMessage(net.iGap.proto.ProtoGlobal.Pagination.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pagination_);
                pagination_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoMplTransactionList.MplTransactionList.class, net.iGap.proto.ProtoMplTransactionList.MplTransactionList.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .proto.MplTransaction.Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .proto.MplTransaction.Type type = 2;</code>
     */
    public net.iGap.proto.ProtoGlobal.MplTransaction.Type getType() {
      net.iGap.proto.ProtoGlobal.MplTransaction.Type result = net.iGap.proto.ProtoGlobal.MplTransaction.Type.valueOf(type_);
      return result == null ? net.iGap.proto.ProtoGlobal.MplTransaction.Type.UNRECOGNIZED : result;
    }

    public static final int PAGINATION_FIELD_NUMBER = 3;
    private net.iGap.proto.ProtoGlobal.Pagination pagination_;
    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    public boolean hasPagination() {
      return pagination_ != null;
    }
    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    public net.iGap.proto.ProtoGlobal.Pagination getPagination() {
      return pagination_ == null ? net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
    }
    /**
     * <code>optional .proto.Pagination pagination = 3;</code>
     */
    public net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder() {
      return getPagination();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (type_ != net.iGap.proto.ProtoGlobal.MplTransaction.Type.NONE.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (pagination_ != null) {
        output.writeMessage(3, getPagination());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (type_ != net.iGap.proto.ProtoGlobal.MplTransaction.Type.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (pagination_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPagination());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoMplTransactionList.MplTransactionList)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoMplTransactionList.MplTransactionList other = (net.iGap.proto.ProtoMplTransactionList.MplTransactionList) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && type_ == other.type_;
      result = result && (hasPagination() == other.hasPagination());
      if (hasPagination()) {
        result = result && getPagination()
            .equals(other.getPagination());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasPagination()) {
        hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
        hash = (53 * hash) + getPagination().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoMplTransactionList.MplTransactionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplTransactionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplTransactionList)
        net.iGap.proto.ProtoMplTransactionList.MplTransactionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoMplTransactionList.MplTransactionList.class, net.iGap.proto.ProtoMplTransactionList.MplTransactionList.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoMplTransactionList.MplTransactionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        type_ = 0;

        if (paginationBuilder_ == null) {
          pagination_ = null;
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionList_descriptor;
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionList getDefaultInstanceForType() {
        return net.iGap.proto.ProtoMplTransactionList.MplTransactionList.getDefaultInstance();
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionList build() {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionList buildPartial() {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionList result = new net.iGap.proto.ProtoMplTransactionList.MplTransactionList(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.type_ = type_;
        if (paginationBuilder_ == null) {
          result.pagination_ = pagination_;
        } else {
          result.pagination_ = paginationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoMplTransactionList.MplTransactionList) {
          return mergeFrom((net.iGap.proto.ProtoMplTransactionList.MplTransactionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoMplTransactionList.MplTransactionList other) {
        if (other == net.iGap.proto.ProtoMplTransactionList.MplTransactionList.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasPagination()) {
          mergePagination(other.getPagination());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoMplTransactionList.MplTransactionList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>optional .proto.MplTransaction.Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .proto.MplTransaction.Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.MplTransaction.Type type = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransaction.Type getType() {
        net.iGap.proto.ProtoGlobal.MplTransaction.Type result = net.iGap.proto.ProtoGlobal.MplTransaction.Type.valueOf(type_);
        return result == null ? net.iGap.proto.ProtoGlobal.MplTransaction.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.MplTransaction.Type type = 2;</code>
       */
      public Builder setType(net.iGap.proto.ProtoGlobal.MplTransaction.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.MplTransaction.Type type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private net.iGap.proto.ProtoGlobal.Pagination pagination_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder> paginationBuilder_;
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public boolean hasPagination() {
        return paginationBuilder_ != null || pagination_ != null;
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Pagination getPagination() {
        if (paginationBuilder_ == null) {
          return pagination_ == null ? net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
        } else {
          return paginationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public Builder setPagination(net.iGap.proto.ProtoGlobal.Pagination value) {
        if (paginationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pagination_ = value;
          onChanged();
        } else {
          paginationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public Builder setPagination(
          net.iGap.proto.ProtoGlobal.Pagination.Builder builderForValue) {
        if (paginationBuilder_ == null) {
          pagination_ = builderForValue.build();
          onChanged();
        } else {
          paginationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public Builder mergePagination(net.iGap.proto.ProtoGlobal.Pagination value) {
        if (paginationBuilder_ == null) {
          if (pagination_ != null) {
            pagination_ =
              net.iGap.proto.ProtoGlobal.Pagination.newBuilder(pagination_).mergeFrom(value).buildPartial();
          } else {
            pagination_ = value;
          }
          onChanged();
        } else {
          paginationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public Builder clearPagination() {
        if (paginationBuilder_ == null) {
          pagination_ = null;
          onChanged();
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.Pagination.Builder getPaginationBuilder() {
        
        onChanged();
        return getPaginationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      public net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder() {
        if (paginationBuilder_ != null) {
          return paginationBuilder_.getMessageOrBuilder();
        } else {
          return pagination_ == null ?
              net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
        }
      }
      /**
       * <code>optional .proto.Pagination pagination = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder> 
          getPaginationFieldBuilder() {
        if (paginationBuilder_ == null) {
          paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder>(
                  getPagination(),
                  getParentForChildren(),
                  isClean());
          pagination_ = null;
        }
        return paginationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MplTransactionList)
    }

    // @@protoc_insertion_point(class_scope:proto.MplTransactionList)
    private static final net.iGap.proto.ProtoMplTransactionList.MplTransactionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoMplTransactionList.MplTransactionList();
    }

    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplTransactionList>
        PARSER = new com.google.protobuf.AbstractParser<MplTransactionList>() {
      public MplTransactionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MplTransactionList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplTransactionList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplTransactionList> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoMplTransactionList.MplTransactionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MplTransactionListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplTransactionListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction> 
        getTransactionList();
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.MplTransaction getTransaction(int index);
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    int getTransactionCount();
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    java.util.List<? extends net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder> 
        getTransactionOrBuilderList();
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder getTransactionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.MplTransactionListResponse}
   */
  public  static final class MplTransactionListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplTransactionListResponse)
      MplTransactionListResponseOrBuilder {
    // Use MplTransactionListResponse.newBuilder() to construct.
    private MplTransactionListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplTransactionListResponse() {
      transaction_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MplTransactionListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                transaction_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.MplTransaction>();
                mutable_bitField0_ |= 0x00000002;
              }
              transaction_.add(
                  input.readMessage(net.iGap.proto.ProtoGlobal.MplTransaction.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          transaction_ = java.util.Collections.unmodifiableList(transaction_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.class, net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int TRANSACTION_FIELD_NUMBER = 2;
    private java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction> transaction_;
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    public java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction> getTransactionList() {
      return transaction_;
    }
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    public java.util.List<? extends net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder> 
        getTransactionOrBuilderList() {
      return transaction_;
    }
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    public int getTransactionCount() {
      return transaction_.size();
    }
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    public net.iGap.proto.ProtoGlobal.MplTransaction getTransaction(int index) {
      return transaction_.get(index);
    }
    /**
     * <code>repeated .proto.MplTransaction transaction = 2;</code>
     */
    public net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder getTransactionOrBuilder(
        int index) {
      return transaction_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < transaction_.size(); i++) {
        output.writeMessage(2, transaction_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < transaction_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, transaction_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse other = (net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && getTransactionList()
          .equals(other.getTransactionList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (getTransactionCount() > 0) {
        hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplTransactionListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplTransactionListResponse)
        net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.class, net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        if (transactionBuilder_ == null) {
          transaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          transactionBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoMplTransactionList.internal_static_proto_MplTransactionListResponse_descriptor;
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.getDefaultInstance();
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse build() {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse buildPartial() {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse result = new net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (transactionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            transaction_ = java.util.Collections.unmodifiableList(transaction_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.transaction_ = transaction_;
        } else {
          result.transaction_ = transactionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse) {
          return mergeFrom((net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse other) {
        if (other == net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (transactionBuilder_ == null) {
          if (!other.transaction_.isEmpty()) {
            if (transaction_.isEmpty()) {
              transaction_ = other.transaction_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTransactionIsMutable();
              transaction_.addAll(other.transaction_);
            }
            onChanged();
          }
        } else {
          if (!other.transaction_.isEmpty()) {
            if (transactionBuilder_.isEmpty()) {
              transactionBuilder_.dispose();
              transactionBuilder_ = null;
              transaction_ = other.transaction_;
              bitField0_ = (bitField0_ & ~0x00000002);
              transactionBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionFieldBuilder() : null;
            } else {
              transactionBuilder_.addAllMessages(other.transaction_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction> transaction_ =
        java.util.Collections.emptyList();
      private void ensureTransactionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          transaction_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.MplTransaction>(transaction_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.MplTransaction, net.iGap.proto.ProtoGlobal.MplTransaction.Builder, net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder> transactionBuilder_;

      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction> getTransactionList() {
        if (transactionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transaction_);
        } else {
          return transactionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public int getTransactionCount() {
        if (transactionBuilder_ == null) {
          return transaction_.size();
        } else {
          return transactionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransaction getTransaction(int index) {
        if (transactionBuilder_ == null) {
          return transaction_.get(index);
        } else {
          return transactionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder setTransaction(
          int index, net.iGap.proto.ProtoGlobal.MplTransaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.set(index, value);
          onChanged();
        } else {
          transactionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder setTransaction(
          int index, net.iGap.proto.ProtoGlobal.MplTransaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder addTransaction(net.iGap.proto.ProtoGlobal.MplTransaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.add(value);
          onChanged();
        } else {
          transactionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder addTransaction(
          int index, net.iGap.proto.ProtoGlobal.MplTransaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.add(index, value);
          onChanged();
        } else {
          transactionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder addTransaction(
          net.iGap.proto.ProtoGlobal.MplTransaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.add(builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder addTransaction(
          int index, net.iGap.proto.ProtoGlobal.MplTransaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder addAllTransaction(
          java.lang.Iterable<? extends net.iGap.proto.ProtoGlobal.MplTransaction> values) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transaction_);
          onChanged();
        } else {
          transactionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder clearTransaction() {
        if (transactionBuilder_ == null) {
          transaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          transactionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public Builder removeTransaction(int index) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.remove(index);
          onChanged();
        } else {
          transactionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransaction.Builder getTransactionBuilder(
          int index) {
        return getTransactionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder getTransactionOrBuilder(
          int index) {
        if (transactionBuilder_ == null) {
          return transaction_.get(index);  } else {
          return transactionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public java.util.List<? extends net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder> 
           getTransactionOrBuilderList() {
        if (transactionBuilder_ != null) {
          return transactionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transaction_);
        }
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransaction.Builder addTransactionBuilder() {
        return getTransactionFieldBuilder().addBuilder(
            net.iGap.proto.ProtoGlobal.MplTransaction.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplTransaction.Builder addTransactionBuilder(
          int index) {
        return getTransactionFieldBuilder().addBuilder(
            index, net.iGap.proto.ProtoGlobal.MplTransaction.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.MplTransaction transaction = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.MplTransaction.Builder> 
           getTransactionBuilderList() {
        return getTransactionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.MplTransaction, net.iGap.proto.ProtoGlobal.MplTransaction.Builder, net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder> 
          getTransactionFieldBuilder() {
        if (transactionBuilder_ == null) {
          transactionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.MplTransaction, net.iGap.proto.ProtoGlobal.MplTransaction.Builder, net.iGap.proto.ProtoGlobal.MplTransactionOrBuilder>(
                  transaction_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          transaction_ = null;
        }
        return transactionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MplTransactionListResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.MplTransactionListResponse)
    private static final net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse();
    }

    public static net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplTransactionListResponse>
        PARSER = new com.google.protobuf.AbstractParser<MplTransactionListResponse>() {
      public MplTransactionListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MplTransactionListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplTransactionListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplTransactionListResponse> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoMplTransactionList.MplTransactionListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplTransactionList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplTransactionList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplTransactionListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplTransactionListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MplTransactionList.proto\022\005proto\032\rReque" +
      "st.proto\032\016Response.proto\032\014Global.proto\"\206" +
      "\001\n\022MplTransactionList\022\037\n\007request\030\001 \001(\0132\016" +
      ".proto.Request\022(\n\004type\030\002 \001(\0162\032.proto.Mpl" +
      "Transaction.Type\022%\n\npagination\030\003 \001(\0132\021.p" +
      "roto.Pagination\"k\n\032MplTransactionListRes" +
      "ponse\022!\n\010response\030\001 \001(\0132\017.proto.Response" +
      "\022*\n\013transaction\030\002 \003(\0132\025.proto.MplTransac" +
      "tionB)\n\016net.iGap.protoB\027ProtoMplTransact" +
      "ionListb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        }, assigner);
    internal_static_proto_MplTransactionList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MplTransactionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplTransactionList_descriptor,
        new java.lang.String[] { "Request", "Type", "Pagination", });
    internal_static_proto_MplTransactionListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MplTransactionListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplTransactionListResponse_descriptor,
        new java.lang.String[] { "Response", "Transaction", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
