// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MplSalesConfirm.proto

package net.iGap.proto;

public final class ProtoMplSalesConfirm {
  private ProtoMplSalesConfirm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MplSalesConfirmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplSalesConfirm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional uint64 invoice_number = 2;</code>
     */
    long getInvoiceNumber();

    /**
     * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
     */
    int getConfirmValue();
    /**
     * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
     */
    net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm getConfirm();
  }
  /**
   * Protobuf type {@code proto.MplSalesConfirm}
   */
  public  static final class MplSalesConfirm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplSalesConfirm)
      MplSalesConfirmOrBuilder {
    // Use MplSalesConfirm.newBuilder() to construct.
    private MplSalesConfirm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplSalesConfirm() {
      invoiceNumber_ = 0L;
      confirm_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MplSalesConfirm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              invoiceNumber_ = input.readUInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              confirm_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.class, net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.MplSalesConfirm.Confirm}
     */
    public enum Confirm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONFIRM = 0;</code>
       */
      CONFIRM(0),
      /**
       * <code>REVERSE = 1;</code>
       */
      REVERSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CONFIRM = 0;</code>
       */
      public static final int CONFIRM_VALUE = 0;
      /**
       * <code>REVERSE = 1;</code>
       */
      public static final int REVERSE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Confirm valueOf(int value) {
        return forNumber(value);
      }

      public static Confirm forNumber(int value) {
        switch (value) {
          case 0: return CONFIRM;
          case 1: return REVERSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Confirm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Confirm> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Confirm>() {
              public Confirm findValueByNumber(int number) {
                return Confirm.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.getDescriptor().getEnumTypes().get(0);
      }

      private static final Confirm[] VALUES = values();

      public static Confirm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Confirm(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.MplSalesConfirm.Confirm)
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int INVOICE_NUMBER_FIELD_NUMBER = 2;
    private long invoiceNumber_;
    /**
     * <code>optional uint64 invoice_number = 2;</code>
     */
    public long getInvoiceNumber() {
      return invoiceNumber_;
    }

    public static final int CONFIRM_FIELD_NUMBER = 3;
    private int confirm_;
    /**
     * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
     */
    public int getConfirmValue() {
      return confirm_;
    }
    /**
     * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
     */
    public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm getConfirm() {
      net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm result = net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.valueOf(confirm_);
      return result == null ? net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (invoiceNumber_ != 0L) {
        output.writeUInt64(2, invoiceNumber_);
      }
      if (confirm_ != net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.CONFIRM.getNumber()) {
        output.writeEnum(3, confirm_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (invoiceNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, invoiceNumber_);
      }
      if (confirm_ != net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.CONFIRM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, confirm_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm other = (net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (getInvoiceNumber()
          == other.getInvoiceNumber());
      result = result && confirm_ == other.confirm_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + INVOICE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvoiceNumber());
      hash = (37 * hash) + CONFIRM_FIELD_NUMBER;
      hash = (53 * hash) + confirm_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplSalesConfirm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplSalesConfirm)
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.class, net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        invoiceNumber_ = 0L;

        confirm_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirm_descriptor;
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm getDefaultInstanceForType() {
        return net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.getDefaultInstance();
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm build() {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm buildPartial() {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm result = new net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.invoiceNumber_ = invoiceNumber_;
        result.confirm_ = confirm_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm) {
          return mergeFrom((net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm other) {
        if (other == net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getInvoiceNumber() != 0L) {
          setInvoiceNumber(other.getInvoiceNumber());
        }
        if (other.confirm_ != 0) {
          setConfirmValue(other.getConfirmValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long invoiceNumber_ ;
      /**
       * <code>optional uint64 invoice_number = 2;</code>
       */
      public long getInvoiceNumber() {
        return invoiceNumber_;
      }
      /**
       * <code>optional uint64 invoice_number = 2;</code>
       */
      public Builder setInvoiceNumber(long value) {
        
        invoiceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 invoice_number = 2;</code>
       */
      public Builder clearInvoiceNumber() {
        
        invoiceNumber_ = 0L;
        onChanged();
        return this;
      }

      private int confirm_ = 0;
      /**
       * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
       */
      public int getConfirmValue() {
        return confirm_;
      }
      /**
       * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
       */
      public Builder setConfirmValue(int value) {
        confirm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
       */
      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm getConfirm() {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm result = net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.valueOf(confirm_);
        return result == null ? net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
       */
      public Builder setConfirm(net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm.Confirm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        confirm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.MplSalesConfirm.Confirm confirm = 3;</code>
       */
      public Builder clearConfirm() {
        
        confirm_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MplSalesConfirm)
    }

    // @@protoc_insertion_point(class_scope:proto.MplSalesConfirm)
    private static final net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm();
    }

    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplSalesConfirm>
        PARSER = new com.google.protobuf.AbstractParser<MplSalesConfirm>() {
      public MplSalesConfirm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MplSalesConfirm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplSalesConfirm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplSalesConfirm> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MplSalesConfirmResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplSalesConfirmResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    boolean hasSale();
    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.MplSale getSale();
    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.MplSaleOrBuilder getSaleOrBuilder();
  }
  /**
   * Protobuf type {@code proto.MplSalesConfirmResponse}
   */
  public  static final class MplSalesConfirmResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplSalesConfirmResponse)
      MplSalesConfirmResponseOrBuilder {
    // Use MplSalesConfirmResponse.newBuilder() to construct.
    private MplSalesConfirmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplSalesConfirmResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MplSalesConfirmResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              net.iGap.proto.ProtoGlobal.MplSale.Builder subBuilder = null;
              if (sale_ != null) {
                subBuilder = sale_.toBuilder();
              }
              sale_ = input.readMessage(net.iGap.proto.ProtoGlobal.MplSale.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sale_);
                sale_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirmResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.class, net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int SALE_FIELD_NUMBER = 2;
    private net.iGap.proto.ProtoGlobal.MplSale sale_;
    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    public boolean hasSale() {
      return sale_ != null;
    }
    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    public net.iGap.proto.ProtoGlobal.MplSale getSale() {
      return sale_ == null ? net.iGap.proto.ProtoGlobal.MplSale.getDefaultInstance() : sale_;
    }
    /**
     * <code>optional .proto.MplSale sale = 2;</code>
     */
    public net.iGap.proto.ProtoGlobal.MplSaleOrBuilder getSaleOrBuilder() {
      return getSale();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (sale_ != null) {
        output.writeMessage(2, getSale());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (sale_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSale());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse other = (net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && (hasSale() == other.hasSale());
      if (hasSale()) {
        result = result && getSale()
            .equals(other.getSale());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasSale()) {
        hash = (37 * hash) + SALE_FIELD_NUMBER;
        hash = (53 * hash) + getSale().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplSalesConfirmResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplSalesConfirmResponse)
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirmResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirmResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.class, net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        if (saleBuilder_ == null) {
          sale_ = null;
        } else {
          sale_ = null;
          saleBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoMplSalesConfirm.internal_static_proto_MplSalesConfirmResponse_descriptor;
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.getDefaultInstance();
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse build() {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse buildPartial() {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse result = new net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (saleBuilder_ == null) {
          result.sale_ = sale_;
        } else {
          result.sale_ = saleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse) {
          return mergeFrom((net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse other) {
        if (other == net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasSale()) {
          mergeSale(other.getSale());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private net.iGap.proto.ProtoGlobal.MplSale sale_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.MplSale, net.iGap.proto.ProtoGlobal.MplSale.Builder, net.iGap.proto.ProtoGlobal.MplSaleOrBuilder> saleBuilder_;
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public boolean hasSale() {
        return saleBuilder_ != null || sale_ != null;
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplSale getSale() {
        if (saleBuilder_ == null) {
          return sale_ == null ? net.iGap.proto.ProtoGlobal.MplSale.getDefaultInstance() : sale_;
        } else {
          return saleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public Builder setSale(net.iGap.proto.ProtoGlobal.MplSale value) {
        if (saleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sale_ = value;
          onChanged();
        } else {
          saleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public Builder setSale(
          net.iGap.proto.ProtoGlobal.MplSale.Builder builderForValue) {
        if (saleBuilder_ == null) {
          sale_ = builderForValue.build();
          onChanged();
        } else {
          saleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public Builder mergeSale(net.iGap.proto.ProtoGlobal.MplSale value) {
        if (saleBuilder_ == null) {
          if (sale_ != null) {
            sale_ =
              net.iGap.proto.ProtoGlobal.MplSale.newBuilder(sale_).mergeFrom(value).buildPartial();
          } else {
            sale_ = value;
          }
          onChanged();
        } else {
          saleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public Builder clearSale() {
        if (saleBuilder_ == null) {
          sale_ = null;
          onChanged();
        } else {
          sale_ = null;
          saleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplSale.Builder getSaleBuilder() {
        
        onChanged();
        return getSaleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.MplSaleOrBuilder getSaleOrBuilder() {
        if (saleBuilder_ != null) {
          return saleBuilder_.getMessageOrBuilder();
        } else {
          return sale_ == null ?
              net.iGap.proto.ProtoGlobal.MplSale.getDefaultInstance() : sale_;
        }
      }
      /**
       * <code>optional .proto.MplSale sale = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.MplSale, net.iGap.proto.ProtoGlobal.MplSale.Builder, net.iGap.proto.ProtoGlobal.MplSaleOrBuilder> 
          getSaleFieldBuilder() {
        if (saleBuilder_ == null) {
          saleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.MplSale, net.iGap.proto.ProtoGlobal.MplSale.Builder, net.iGap.proto.ProtoGlobal.MplSaleOrBuilder>(
                  getSale(),
                  getParentForChildren(),
                  isClean());
          sale_ = null;
        }
        return saleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MplSalesConfirmResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.MplSalesConfirmResponse)
    private static final net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse();
    }

    public static net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplSalesConfirmResponse>
        PARSER = new com.google.protobuf.AbstractParser<MplSalesConfirmResponse>() {
      public MplSalesConfirmResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MplSalesConfirmResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplSalesConfirmResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplSalesConfirmResponse> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoMplSalesConfirm.MplSalesConfirmResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplSalesConfirm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplSalesConfirm_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplSalesConfirmResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplSalesConfirmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MplSalesConfirm.proto\022\005proto\032\rRequest." +
      "proto\032\016Response.proto\032\014Global.proto\"\240\001\n\017" +
      "MplSalesConfirm\022\037\n\007request\030\001 \001(\0132\016.proto" +
      ".Request\022\026\n\016invoice_number\030\002 \001(\004\022/\n\007conf" +
      "irm\030\003 \001(\0162\036.proto.MplSalesConfirm.Confir" +
      "m\"#\n\007Confirm\022\013\n\007CONFIRM\020\000\022\013\n\007REVERSE\020\001\"Z" +
      "\n\027MplSalesConfirmResponse\022!\n\010response\030\001 " +
      "\001(\0132\017.proto.Response\022\034\n\004sale\030\002 \001(\0132\016.pro" +
      "to.MplSaleB&\n\016net.iGap.protoB\024ProtoMplSa" +
      "lesConfirmb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        }, assigner);
    internal_static_proto_MplSalesConfirm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MplSalesConfirm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplSalesConfirm_descriptor,
        new java.lang.String[] { "Request", "InvoiceNumber", "Confirm", });
    internal_static_proto_MplSalesConfirmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MplSalesConfirmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplSalesConfirmResponse_descriptor,
        new java.lang.String[] { "Response", "Sale", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
