// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelAddAdmin.proto

package net.iGap.proto;

public final class ProtoChannelAddAdmin {
  private ProtoChannelAddAdmin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelAddAdminOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChannelAddAdmin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    long getRoomId();

    /**
     * <code>optional uint64 member_id = 3;</code>
     */
    long getMemberId();

    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    boolean hasPermission();
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission();
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder();
  }
  /**
   * Protobuf type {@code proto.ChannelAddAdmin}
   */
  public  static final class ChannelAddAdmin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChannelAddAdmin)
      ChannelAddAdminOrBuilder {
    // Use ChannelAddAdmin.newBuilder() to construct.
    private ChannelAddAdmin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAddAdmin() {
      roomId_ = 0L;
      memberId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChannelAddAdmin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            case 24: {

              memberId_ = input.readUInt64();
              break;
            }
            case 34: {
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder subBuilder = null;
              if (permission_ != null) {
                subBuilder = permission_.toBuilder();
              }
              permission_ = input.readMessage(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(permission_);
                permission_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.Builder.class);
    }

    public interface AdminRightsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.ChannelAddAdmin.AdminRights)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bool modify_room = 1;</code>
       */
      boolean getModifyRoom();

      /**
       * <code>optional bool post_message = 2;</code>
       */
      boolean getPostMessage();

      /**
       * <code>optional bool edit_message = 3;</code>
       */
      boolean getEditMessage();

      /**
       * <code>optional bool delete_message = 4;</code>
       */
      boolean getDeleteMessage();

      /**
       * <code>optional bool pin_message = 5;</code>
       */
      boolean getPinMessage();

      /**
       * <code>optional bool add_member = 6;</code>
       */
      boolean getAddMember();

      /**
       * <code>optional bool ban_member = 7;</code>
       */
      boolean getBanMember();

      /**
       * <code>optional bool get_member = 8;</code>
       */
      boolean getGetMember();

      /**
       * <code>optional bool add_admin = 9;</code>
       */
      boolean getAddAdmin();
    }
    /**
     * Protobuf type {@code proto.ChannelAddAdmin.AdminRights}
     */
    public  static final class AdminRights extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:proto.ChannelAddAdmin.AdminRights)
        AdminRightsOrBuilder {
      // Use AdminRights.newBuilder() to construct.
      private AdminRights(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private AdminRights() {
        modifyRoom_ = false;
        postMessage_ = false;
        editMessage_ = false;
        deleteMessage_ = false;
        pinMessage_ = false;
        addMember_ = false;
        banMember_ = false;
        getMember_ = false;
        addAdmin_ = false;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private AdminRights(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                modifyRoom_ = input.readBool();
                break;
              }
              case 16: {

                postMessage_ = input.readBool();
                break;
              }
              case 24: {

                editMessage_ = input.readBool();
                break;
              }
              case 32: {

                deleteMessage_ = input.readBool();
                break;
              }
              case 40: {

                pinMessage_ = input.readBool();
                break;
              }
              case 48: {

                addMember_ = input.readBool();
                break;
              }
              case 56: {

                banMember_ = input.readBool();
                break;
              }
              case 64: {

                getMember_ = input.readBool();
                break;
              }
              case 72: {

                addAdmin_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_AdminRights_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_AdminRights_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder.class);
      }

      public static final int MODIFY_ROOM_FIELD_NUMBER = 1;
      private boolean modifyRoom_;
      /**
       * <code>optional bool modify_room = 1;</code>
       */
      public boolean getModifyRoom() {
        return modifyRoom_;
      }

      public static final int POST_MESSAGE_FIELD_NUMBER = 2;
      private boolean postMessage_;
      /**
       * <code>optional bool post_message = 2;</code>
       */
      public boolean getPostMessage() {
        return postMessage_;
      }

      public static final int EDIT_MESSAGE_FIELD_NUMBER = 3;
      private boolean editMessage_;
      /**
       * <code>optional bool edit_message = 3;</code>
       */
      public boolean getEditMessage() {
        return editMessage_;
      }

      public static final int DELETE_MESSAGE_FIELD_NUMBER = 4;
      private boolean deleteMessage_;
      /**
       * <code>optional bool delete_message = 4;</code>
       */
      public boolean getDeleteMessage() {
        return deleteMessage_;
      }

      public static final int PIN_MESSAGE_FIELD_NUMBER = 5;
      private boolean pinMessage_;
      /**
       * <code>optional bool pin_message = 5;</code>
       */
      public boolean getPinMessage() {
        return pinMessage_;
      }

      public static final int ADD_MEMBER_FIELD_NUMBER = 6;
      private boolean addMember_;
      /**
       * <code>optional bool add_member = 6;</code>
       */
      public boolean getAddMember() {
        return addMember_;
      }

      public static final int BAN_MEMBER_FIELD_NUMBER = 7;
      private boolean banMember_;
      /**
       * <code>optional bool ban_member = 7;</code>
       */
      public boolean getBanMember() {
        return banMember_;
      }

      public static final int GET_MEMBER_FIELD_NUMBER = 8;
      private boolean getMember_;
      /**
       * <code>optional bool get_member = 8;</code>
       */
      public boolean getGetMember() {
        return getMember_;
      }

      public static final int ADD_ADMIN_FIELD_NUMBER = 9;
      private boolean addAdmin_;
      /**
       * <code>optional bool add_admin = 9;</code>
       */
      public boolean getAddAdmin() {
        return addAdmin_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (modifyRoom_ != false) {
          output.writeBool(1, modifyRoom_);
        }
        if (postMessage_ != false) {
          output.writeBool(2, postMessage_);
        }
        if (editMessage_ != false) {
          output.writeBool(3, editMessage_);
        }
        if (deleteMessage_ != false) {
          output.writeBool(4, deleteMessage_);
        }
        if (pinMessage_ != false) {
          output.writeBool(5, pinMessage_);
        }
        if (addMember_ != false) {
          output.writeBool(6, addMember_);
        }
        if (banMember_ != false) {
          output.writeBool(7, banMember_);
        }
        if (getMember_ != false) {
          output.writeBool(8, getMember_);
        }
        if (addAdmin_ != false) {
          output.writeBool(9, addAdmin_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (modifyRoom_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, modifyRoom_);
        }
        if (postMessage_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, postMessage_);
        }
        if (editMessage_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, editMessage_);
        }
        if (deleteMessage_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, deleteMessage_);
        }
        if (pinMessage_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(5, pinMessage_);
        }
        if (addMember_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(6, addMember_);
        }
        if (banMember_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(7, banMember_);
        }
        if (getMember_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(8, getMember_);
        }
        if (addAdmin_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(9, addAdmin_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights)) {
          return super.equals(obj);
        }
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights other = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights) obj;

        boolean result = true;
        result = result && (getModifyRoom()
            == other.getModifyRoom());
        result = result && (getPostMessage()
            == other.getPostMessage());
        result = result && (getEditMessage()
            == other.getEditMessage());
        result = result && (getDeleteMessage()
            == other.getDeleteMessage());
        result = result && (getPinMessage()
            == other.getPinMessage());
        result = result && (getAddMember()
            == other.getAddMember());
        result = result && (getBanMember()
            == other.getBanMember());
        result = result && (getGetMember()
            == other.getGetMember());
        result = result && (getAddAdmin()
            == other.getAddAdmin());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + MODIFY_ROOM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getModifyRoom());
        hash = (37 * hash) + POST_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPostMessage());
        hash = (37 * hash) + EDIT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEditMessage());
        hash = (37 * hash) + DELETE_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDeleteMessage());
        hash = (37 * hash) + PIN_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPinMessage());
        hash = (37 * hash) + ADD_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAddMember());
        hash = (37 * hash) + BAN_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBanMember());
        hash = (37 * hash) + GET_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGetMember());
        hash = (37 * hash) + ADD_ADMIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAddAdmin());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.ChannelAddAdmin.AdminRights}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.ChannelAddAdmin.AdminRights)
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_AdminRights_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_AdminRights_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder.class);
        }

        // Construct using net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          modifyRoom_ = false;

          postMessage_ = false;

          editMessage_ = false;

          deleteMessage_ = false;

          pinMessage_ = false;

          addMember_ = false;

          banMember_ = false;

          getMember_ = false;

          addAdmin_ = false;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_AdminRights_descriptor;
        }

        public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getDefaultInstanceForType() {
          return net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance();
        }

        public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights build() {
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights buildPartial() {
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights result = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights(this);
          result.modifyRoom_ = modifyRoom_;
          result.postMessage_ = postMessage_;
          result.editMessage_ = editMessage_;
          result.deleteMessage_ = deleteMessage_;
          result.pinMessage_ = pinMessage_;
          result.addMember_ = addMember_;
          result.banMember_ = banMember_;
          result.getMember_ = getMember_;
          result.addAdmin_ = addAdmin_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights) {
            return mergeFrom((net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights other) {
          if (other == net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance()) return this;
          if (other.getModifyRoom() != false) {
            setModifyRoom(other.getModifyRoom());
          }
          if (other.getPostMessage() != false) {
            setPostMessage(other.getPostMessage());
          }
          if (other.getEditMessage() != false) {
            setEditMessage(other.getEditMessage());
          }
          if (other.getDeleteMessage() != false) {
            setDeleteMessage(other.getDeleteMessage());
          }
          if (other.getPinMessage() != false) {
            setPinMessage(other.getPinMessage());
          }
          if (other.getAddMember() != false) {
            setAddMember(other.getAddMember());
          }
          if (other.getBanMember() != false) {
            setBanMember(other.getBanMember());
          }
          if (other.getGetMember() != false) {
            setGetMember(other.getGetMember());
          }
          if (other.getAddAdmin() != false) {
            setAddAdmin(other.getAddAdmin());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private boolean modifyRoom_ ;
        /**
         * <code>optional bool modify_room = 1;</code>
         */
        public boolean getModifyRoom() {
          return modifyRoom_;
        }
        /**
         * <code>optional bool modify_room = 1;</code>
         */
        public Builder setModifyRoom(boolean value) {
          
          modifyRoom_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool modify_room = 1;</code>
         */
        public Builder clearModifyRoom() {
          
          modifyRoom_ = false;
          onChanged();
          return this;
        }

        private boolean postMessage_ ;
        /**
         * <code>optional bool post_message = 2;</code>
         */
        public boolean getPostMessage() {
          return postMessage_;
        }
        /**
         * <code>optional bool post_message = 2;</code>
         */
        public Builder setPostMessage(boolean value) {
          
          postMessage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool post_message = 2;</code>
         */
        public Builder clearPostMessage() {
          
          postMessage_ = false;
          onChanged();
          return this;
        }

        private boolean editMessage_ ;
        /**
         * <code>optional bool edit_message = 3;</code>
         */
        public boolean getEditMessage() {
          return editMessage_;
        }
        /**
         * <code>optional bool edit_message = 3;</code>
         */
        public Builder setEditMessage(boolean value) {
          
          editMessage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool edit_message = 3;</code>
         */
        public Builder clearEditMessage() {
          
          editMessage_ = false;
          onChanged();
          return this;
        }

        private boolean deleteMessage_ ;
        /**
         * <code>optional bool delete_message = 4;</code>
         */
        public boolean getDeleteMessage() {
          return deleteMessage_;
        }
        /**
         * <code>optional bool delete_message = 4;</code>
         */
        public Builder setDeleteMessage(boolean value) {
          
          deleteMessage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool delete_message = 4;</code>
         */
        public Builder clearDeleteMessage() {
          
          deleteMessage_ = false;
          onChanged();
          return this;
        }

        private boolean pinMessage_ ;
        /**
         * <code>optional bool pin_message = 5;</code>
         */
        public boolean getPinMessage() {
          return pinMessage_;
        }
        /**
         * <code>optional bool pin_message = 5;</code>
         */
        public Builder setPinMessage(boolean value) {
          
          pinMessage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool pin_message = 5;</code>
         */
        public Builder clearPinMessage() {
          
          pinMessage_ = false;
          onChanged();
          return this;
        }

        private boolean addMember_ ;
        /**
         * <code>optional bool add_member = 6;</code>
         */
        public boolean getAddMember() {
          return addMember_;
        }
        /**
         * <code>optional bool add_member = 6;</code>
         */
        public Builder setAddMember(boolean value) {
          
          addMember_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool add_member = 6;</code>
         */
        public Builder clearAddMember() {
          
          addMember_ = false;
          onChanged();
          return this;
        }

        private boolean banMember_ ;
        /**
         * <code>optional bool ban_member = 7;</code>
         */
        public boolean getBanMember() {
          return banMember_;
        }
        /**
         * <code>optional bool ban_member = 7;</code>
         */
        public Builder setBanMember(boolean value) {
          
          banMember_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool ban_member = 7;</code>
         */
        public Builder clearBanMember() {
          
          banMember_ = false;
          onChanged();
          return this;
        }

        private boolean getMember_ ;
        /**
         * <code>optional bool get_member = 8;</code>
         */
        public boolean getGetMember() {
          return getMember_;
        }
        /**
         * <code>optional bool get_member = 8;</code>
         */
        public Builder setGetMember(boolean value) {
          
          getMember_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool get_member = 8;</code>
         */
        public Builder clearGetMember() {
          
          getMember_ = false;
          onChanged();
          return this;
        }

        private boolean addAdmin_ ;
        /**
         * <code>optional bool add_admin = 9;</code>
         */
        public boolean getAddAdmin() {
          return addAdmin_;
        }
        /**
         * <code>optional bool add_admin = 9;</code>
         */
        public Builder setAddAdmin(boolean value) {
          
          addAdmin_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool add_admin = 9;</code>
         */
        public Builder clearAddAdmin() {
          
          addAdmin_ = false;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:proto.ChannelAddAdmin.AdminRights)
      }

      // @@protoc_insertion_point(class_scope:proto.ChannelAddAdmin.AdminRights)
      private static final net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights();
      }

      public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<AdminRights>
          PARSER = new com.google.protobuf.AbstractParser<AdminRights>() {
        public AdminRights parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new AdminRights(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<AdminRights> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<AdminRights> getParserForType() {
        return PARSER;
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int MEMBER_ID_FIELD_NUMBER = 3;
    private long memberId_;
    /**
     * <code>optional uint64 member_id = 3;</code>
     */
    public long getMemberId() {
      return memberId_;
    }

    public static final int PERMISSION_FIELD_NUMBER = 4;
    private net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights permission_;
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public boolean hasPermission() {
      return permission_ != null;
    }
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission() {
      return permission_ == null ? net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
    }
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder() {
      return getPermission();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      if (memberId_ != 0L) {
        output.writeUInt64(3, memberId_);
      }
      if (permission_ != null) {
        output.writeMessage(4, getPermission());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      if (memberId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, memberId_);
      }
      if (permission_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPermission());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin other = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (getRoomId()
          == other.getRoomId());
      result = result && (getMemberId()
          == other.getMemberId());
      result = result && (hasPermission() == other.hasPermission());
      if (hasPermission()) {
        result = result && getPermission()
            .equals(other.getPermission());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + MEMBER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemberId());
      if (hasPermission()) {
        hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
        hash = (53 * hash) + getPermission().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChannelAddAdmin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChannelAddAdmin)
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        memberId_ = 0L;

        if (permissionBuilder_ == null) {
          permission_ = null;
        } else {
          permission_ = null;
          permissionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdmin_descriptor;
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.getDefaultInstance();
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin build() {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin buildPartial() {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin result = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        result.memberId_ = memberId_;
        if (permissionBuilder_ == null) {
          result.permission_ = permission_;
        } else {
          result.permission_ = permissionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin) {
          return mergeFrom((net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin other) {
        if (other == net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getMemberId() != 0L) {
          setMemberId(other.getMemberId());
        }
        if (other.hasPermission()) {
          mergePermission(other.getPermission());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long memberId_ ;
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public long getMemberId() {
        return memberId_;
      }
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public Builder setMemberId(long value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public Builder clearMemberId() {
        
        memberId_ = 0L;
        onChanged();
        return this;
      }

      private net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights permission_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder> permissionBuilder_;
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public boolean hasPermission() {
        return permissionBuilder_ != null || permission_ != null;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission() {
        if (permissionBuilder_ == null) {
          return permission_ == null ? net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
        } else {
          return permissionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder setPermission(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights value) {
        if (permissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          permission_ = value;
          onChanged();
        } else {
          permissionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder setPermission(
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder builderForValue) {
        if (permissionBuilder_ == null) {
          permission_ = builderForValue.build();
          onChanged();
        } else {
          permissionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder mergePermission(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights value) {
        if (permissionBuilder_ == null) {
          if (permission_ != null) {
            permission_ =
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.newBuilder(permission_).mergeFrom(value).buildPartial();
          } else {
            permission_ = value;
          }
          onChanged();
        } else {
          permissionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder clearPermission() {
        if (permissionBuilder_ == null) {
          permission_ = null;
          onChanged();
        } else {
          permission_ = null;
          permissionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder getPermissionBuilder() {
        
        onChanged();
        return getPermissionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder() {
        if (permissionBuilder_ != null) {
          return permissionBuilder_.getMessageOrBuilder();
        } else {
          return permission_ == null ?
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
        }
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder> 
          getPermissionFieldBuilder() {
        if (permissionBuilder_ == null) {
          permissionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder>(
                  getPermission(),
                  getParentForChildren(),
                  isClean());
          permission_ = null;
        }
        return permissionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ChannelAddAdmin)
    }

    // @@protoc_insertion_point(class_scope:proto.ChannelAddAdmin)
    private static final net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin();
    }

    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAddAdmin>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAddAdmin>() {
      public ChannelAddAdmin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChannelAddAdmin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAddAdmin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAddAdmin> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChannelAddAdminResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChannelAddAdminResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    long getRoomId();

    /**
     * <code>optional uint64 member_id = 3;</code>
     */
    long getMemberId();

    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    boolean hasPermission();
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission();
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder();
  }
  /**
   * Protobuf type {@code proto.ChannelAddAdminResponse}
   */
  public  static final class ChannelAddAdminResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChannelAddAdminResponse)
      ChannelAddAdminResponseOrBuilder {
    // Use ChannelAddAdminResponse.newBuilder() to construct.
    private ChannelAddAdminResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAddAdminResponse() {
      roomId_ = 0L;
      memberId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChannelAddAdminResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            case 24: {

              memberId_ = input.readUInt64();
              break;
            }
            case 34: {
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder subBuilder = null;
              if (permission_ != null) {
                subBuilder = permission_.toBuilder();
              }
              permission_ = input.readMessage(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(permission_);
                permission_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdminResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdminResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int MEMBER_ID_FIELD_NUMBER = 3;
    private long memberId_;
    /**
     * <code>optional uint64 member_id = 3;</code>
     */
    public long getMemberId() {
      return memberId_;
    }

    public static final int PERMISSION_FIELD_NUMBER = 4;
    private net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights permission_;
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public boolean hasPermission() {
      return permission_ != null;
    }
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission() {
      return permission_ == null ? net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
    }
    /**
     * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
     */
    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder() {
      return getPermission();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      if (memberId_ != 0L) {
        output.writeUInt64(3, memberId_);
      }
      if (permission_ != null) {
        output.writeMessage(4, getPermission());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      if (memberId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, memberId_);
      }
      if (permission_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPermission());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse other = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && (getRoomId()
          == other.getRoomId());
      result = result && (getMemberId()
          == other.getMemberId());
      result = result && (hasPermission() == other.hasPermission());
      if (hasPermission()) {
        result = result && getPermission()
            .equals(other.getPermission());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + MEMBER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemberId());
      if (hasPermission()) {
        hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
        hash = (53 * hash) + getPermission().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChannelAddAdminResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChannelAddAdminResponse)
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdminResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdminResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.class, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        roomId_ = 0L;

        memberId_ = 0L;

        if (permissionBuilder_ == null) {
          permission_ = null;
        } else {
          permission_ = null;
          permissionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAddAdmin.internal_static_proto_ChannelAddAdminResponse_descriptor;
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.getDefaultInstance();
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse build() {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse buildPartial() {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse result = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.roomId_ = roomId_;
        result.memberId_ = memberId_;
        if (permissionBuilder_ == null) {
          result.permission_ = permission_;
        } else {
          result.permission_ = permissionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse) {
          return mergeFrom((net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse other) {
        if (other == net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getMemberId() != 0L) {
          setMemberId(other.getMemberId());
        }
        if (other.hasPermission()) {
          mergePermission(other.getPermission());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long memberId_ ;
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public long getMemberId() {
        return memberId_;
      }
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public Builder setMemberId(long value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 member_id = 3;</code>
       */
      public Builder clearMemberId() {
        
        memberId_ = 0L;
        onChanged();
        return this;
      }

      private net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights permission_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder> permissionBuilder_;
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public boolean hasPermission() {
        return permissionBuilder_ != null || permission_ != null;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights getPermission() {
        if (permissionBuilder_ == null) {
          return permission_ == null ? net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
        } else {
          return permissionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder setPermission(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights value) {
        if (permissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          permission_ = value;
          onChanged();
        } else {
          permissionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder setPermission(
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder builderForValue) {
        if (permissionBuilder_ == null) {
          permission_ = builderForValue.build();
          onChanged();
        } else {
          permissionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder mergePermission(net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights value) {
        if (permissionBuilder_ == null) {
          if (permission_ != null) {
            permission_ =
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.newBuilder(permission_).mergeFrom(value).buildPartial();
          } else {
            permission_ = value;
          }
          onChanged();
        } else {
          permissionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public Builder clearPermission() {
        if (permissionBuilder_ == null) {
          permission_ = null;
          onChanged();
        } else {
          permission_ = null;
          permissionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder getPermissionBuilder() {
        
        onChanged();
        return getPermissionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder getPermissionOrBuilder() {
        if (permissionBuilder_ != null) {
          return permissionBuilder_.getMessageOrBuilder();
        } else {
          return permission_ == null ?
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.getDefaultInstance() : permission_;
        }
      }
      /**
       * <code>optional .proto.ChannelAddAdmin.AdminRights permission = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder> 
          getPermissionFieldBuilder() {
        if (permissionBuilder_ == null) {
          permissionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRights.Builder, net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdmin.AdminRightsOrBuilder>(
                  getPermission(),
                  getParentForChildren(),
                  isClean());
          permission_ = null;
        }
        return permissionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ChannelAddAdminResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ChannelAddAdminResponse)
    private static final net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse();
    }

    public static net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAddAdminResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAddAdminResponse>() {
      public ChannelAddAdminResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChannelAddAdminResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAddAdminResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAddAdminResponse> getParserForType() {
      return PARSER;
    }

    public net.iGap.proto.ProtoChannelAddAdmin.ChannelAddAdminResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAddAdmin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAddAdmin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAddAdmin_AdminRights_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAddAdmin_AdminRights_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAddAdminResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAddAdminResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ChannelAddAdmin.proto\022\005proto\032\rRequest." +
      "proto\032\016Response.proto\"\333\002\n\017ChannelAddAdmi" +
      "n\022\037\n\007request\030\001 \001(\0132\016.proto.Request\022\017\n\007ro" +
      "om_id\030\002 \001(\004\022\021\n\tmember_id\030\003 \001(\004\0226\n\npermis" +
      "sion\030\004 \001(\0132\".proto.ChannelAddAdmin.Admin" +
      "Rights\032\312\001\n\013AdminRights\022\023\n\013modify_room\030\001 " +
      "\001(\010\022\024\n\014post_message\030\002 \001(\010\022\024\n\014edit_messag" +
      "e\030\003 \001(\010\022\026\n\016delete_message\030\004 \001(\010\022\023\n\013pin_m" +
      "essage\030\005 \001(\010\022\022\n\nadd_member\030\006 \001(\010\022\022\n\nban_" +
      "member\030\007 \001(\010\022\022\n\nget_member\030\010 \001(\010\022\021\n\tadd_",
      "admin\030\t \001(\010\"\230\001\n\027ChannelAddAdminResponse\022" +
      "!\n\010response\030\001 \001(\0132\017.proto.Response\022\017\n\007ro" +
      "om_id\030\002 \001(\004\022\021\n\tmember_id\030\003 \001(\004\0226\n\npermis" +
      "sion\030\004 \001(\0132\".proto.ChannelAddAdmin.Admin" +
      "RightsB&\n\016net.iGap.protoB\024ProtoChannelAd" +
      "dAdminb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
        }, assigner);
    internal_static_proto_ChannelAddAdmin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChannelAddAdmin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAddAdmin_descriptor,
        new java.lang.String[] { "Request", "RoomId", "MemberId", "Permission", });
    internal_static_proto_ChannelAddAdmin_AdminRights_descriptor =
      internal_static_proto_ChannelAddAdmin_descriptor.getNestedTypes().get(0);
    internal_static_proto_ChannelAddAdmin_AdminRights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAddAdmin_AdminRights_descriptor,
        new java.lang.String[] { "ModifyRoom", "PostMessage", "EditMessage", "DeleteMessage", "PinMessage", "AddMember", "BanMember", "GetMember", "AddAdmin", });
    internal_static_proto_ChannelAddAdminResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ChannelAddAdminResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAddAdminResponse_descriptor,
        new java.lang.String[] { "Response", "RoomId", "MemberId", "Permission", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
